# Generated by Django 5.0.6 on 2024-06-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_options_variacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variacao',
            new_name='Categotia',
        ),
        migrations.AlterModelOptions(
            name='categotia',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categoria'},
        ),
    ]
