# Generated by Django 5.0.6 on 2024-06-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_rename_variacao_categotia_alter_categotia_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categotia',
            new_name='Categoria',
        ),
    ]
