# Generated by Django 5.0.6 on 2024-06-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_rename_categotia_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Variacao',
        ),
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
