# Generated by Django 5.0.4 on 2024-07-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_alter_variacao_preco_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='preco_promocional',
            field=models.FloatField(default=0),
        ),
    ]
